filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

- drop_event.when.not.regexp.json.url.path: "^/ebmeds-caregap*"
- drop_event.when.not.equals.json.type: "audit"

- decode_json_fields:
    fields: ["json.request.body"]
    target: "json.request"
    overwrite_keys: true

- include_fields:
    fields: ["json.request.query","json.user.name","json.url.path"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: YWYpHSzmII1G8w7qb6W9
  indices:
    - index: "ebmeds-audit-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
