version: "3.3"

services:
  
  api-gateway:
    image: "quay.io/duodecim/ebmeds-api-gateway:${EBMEDS_VERSION}"
    env_file:
      - ./config.env
    volumes:
      - ./users.json:/app/resource/users.json
    networks:
      - ebmedsnet
    deploy:
      mode: global
    ports:
      - 3001:3001

  engine:
    # listens internally on port 3002 per default
    image: "quay.io/duodecim/ebmeds-engine-master-data:${EBMEDS_VERSION}"
    networks:
      - ebmedsnet
    env_file:
      - ./config.env
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        max_failure_ratio: 0.3

  elasticsearch:
    # listens on port 9200 for REST API traffic and internally on port 9300 for node communication when clustered
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}"
    hostname: "{{.Node.Hostname}}"
    environment:
      - network.host=0.0.0.0
      - node.name={{.Node.Hostname}}
      - cluster.name=ebmeds-logs
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ebmeds-elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - ebmedsnet
    deploy:
      mode: global
      endpoint_mode: dnsrr
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: "docker.elastic.co/kibana/kibana:${ELK_VERSION}"
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    networks:
      - ebmedsnet
    deploy:
      mode: replicated
      replicas: 1 # should be enough
    ports:
      - 5601:5601

  logstash:
      # listens internally on ports 5000 and 5005 for tcp input per default
      image: "docker.elastic.co/logstash/logstash:${ELK_VERSION}"
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
        - ./logstash/pipeline/:/usr/share/logstash/pipeline/
        - ./logstash/ruby/:/usr/share/logstash/ruby/
        - ebmeds-logstash-queue:/usr/share/logstash/data/queue/
      networks:
        - ebmedsnet
      deploy:
        mode: replicated
        replicas: 1

volumes:
  ebmeds-logstash-queue:
  ebmeds-elasticsearch-data:
networks:
  ebmedsnet:

