version: "3"

services:
  api-gateway:
    image: api-gateway
    env_file:
      - api-gateway/config.env
    ports:
      - 3001:3001
    networks:
      - ebmedsnet
    deploy:
      mode: replicated
      replicas: 1

  engine:
    image: engine
    ports:
      - 3002:3002
    networks:
      - ebmedsnet
    env_file:
      - engine/config.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        max_failure_ratio: 0.3

  coaching:
    image: coaching
    networks:
      - ebmedsnet
    env_file:
      - coaching/config.env
    deploy:
      mode: replicated
      replicas: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
       ES_JAVA_OPTS: "-Xms1g -Xmx1g"
       # disable X-Pack
       # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
       #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
       xpack.security.enabled: "false"
       xpack.monitoring.enabled: "false"
       xpack.graph.enabled: "false"
       xpack.watcher.enabled: "false"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ebmedsnet
    deploy:
        mode: replicated # TODO: should be global once we cluster it
        replicas: 1
  #rethinkdb-tmp:
  #  image: rethinkdb:2.3.5


  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - ebmedsnet
    deploy:
      mode: replicated
      replicas: 1 # should be enough
  logstash:
      image: docker.elastic.co/logstash/logstash:5.3.2
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./logstash/pipeline:/usr/share/logstash/pipeline
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        PATH_CONFIG: "/usr/share/logstash/pipeline"
      networks:
        - ebmedsnet
      deploy:
        mode: global

networks:
  ebmedsnet:

# docker network create --driver overlay ebmedsnet
# docker service create --name api-gateway --env-file config/api-gateway.env --constraint 'node.role == manager' --network ebmedsnet --publish 3001:3001 api-gateway
# docker service create --name engine --publish 3002:3002 --network ebmedsnet --env-file config/engine.env --replicas=4 --update-delay 10s --update-parallelism 1 engine
