version: "3"

services:
  api-gateway:
    image: api-gateway
    env_file:
      - api-gateway/config.env
    ports:
      - 3001:3001
    networks:
      - ebmedsnet
    # application logs are handled by the app, but all other stdout output goes here
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12203
    deploy:
      mode: replicated
      replicas: 1

  engine:
    image: engine
    ports:
      - 3002:3002
    networks:
      - ebmedsnet
    env_file:
      - engine/config.env
    depends_on:
      - api-gateway
    # application logs are handled by the app, but all other stdout output goes here
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12203
    deploy:
      mode: replicated
      replicas: 1
      resources:
        # Hard limits
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limits
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        max_failure_ratio: 0.3

networks:
  ebmedsnet:

# volumes:
#   db-data:

# docker network create --driver overlay ebmedsnet
# docker service create --name api-gateway --env-file config/api-gateway.env --constraint 'node.role == manager' --network ebmedsnet --publish 3001:3001 api-gateway
# docker service create --name engine --publish 3002:3002 --network ebmedsnet --env-file config/engine.env --replicas=4 --update-delay 10s --update-parallelism 1 engine
