---
- hosts: app
  tasks:
    - name: Pull latest Coaching Docker image
      shell: 'docker pull quay.io/duodecim/ebmeds-coaching:{{ docker_image_tag }}'

    - name: Tag Coaching Docker image
      shell: 'docker tag quay.io/duodecim/ebmeds-coaching:{{ docker_image_tag }} coaching'

    - name: Perform rolling update for Coaching service
      shell: "docker service update --image $(docker inspect --type image --format {% raw %}'{{.Id}}'{% endraw %} coaching:latest) coaching"
      run_once: true