---
- hosts: app
  tasks:
    - name: Pull latest EBMeDS Engine Docker image
      shell: 'docker pull quay.io/duodecim/ebmeds-engine:{{ docker_image_tag }}'

    - name: Tag EBMeDS Engine Docker image
      shell: 'docker tag quay.io/duodecim/ebmeds-engine:{{ docker_image_tag }} engine'

    - name: Perform rolling update for EBmeDS Engine service
      shell: "docker service update --image $(docker inspect --type image --format {% raw %}'{{.Id}}'{% endraw %} engine:latest) engine"
      run_once: true