---
- hosts: front
  vars:
    scs_repos_schedules:
      scs: monthly1
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - role: scs-repos
      tags: scs-repos
    - role: nginx
      tags: nginx
    - role: keepalived
      tags: keepalived
  tasks:
    - name: Increase incoming connection backlog limit
      sysctl:
        name: net.core.somaxconn
        value: 2048
        state: present
      tags:
        - somaxconn-limit

    - name: Increase max file soft limit
      lineinfile:
        dest: /etc/security/limits.conf
        line: "* soft nofile 65535"
      tags:
        - file-soft-limit
        - file-limit

    - name: Increase max file hard limit
      lineinfile:
        dest: /etc/security/limits.conf
        line: "* hard nofile 65535"
      tags:
        - file-hard-limit
        - file-limit

    - name: Check if SELinux httpd_setrlimit is enabled
      shell: getsebool httpd_setrlimit
      register: selinuxsetrlimit
      changed_when: false
      ignore_errors: true
      tags:
        - nginx
        - nginx-selinux

    - name: Configure SELinux to enable httpd_setrlimit
      command: setsebool -P httpd_setrlimit 1
      when: selinuxsetrlimit.stdout.find("on") == -1
      tags:
        - nginx
        - nginx-selinux

    - name: Copy SSL certificate for NGINX
      copy:
        content: "{{ nginx_ssl_certificate }}"
        dest: /etc/nginx/certs/ebmedscloud.org_bundle.crt
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx
      tags:
        - nginx
        - nginx-certs

    - name: Copy SSL private key for NGINX
      copy:
        content: "{{ nginx_private_key }}"
        dest: /etc/nginx/certs/ebmedscloud.org.key
        owner: root
        group: root
        mode: 0400
      notify:
        - restart nginx
      tags:
        - nginx
        - nginx-private-key

    - name: Install NGINX reverse proxy configuration
      template:
        src: nginx/front_reverse_proxy.conf.j2
        dest: /etc/nginx/conf.d/reverse_proxy.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx
      tags:
        - nginx
        - nginx-reverseproxy-conf

    - name: Check allowed HTTP ports for SELinux
      shell: semanage port --list | grep "^http_port_t"
      register: selinuxhttpports
      changed_when: false
      ignore_errors: true
      tags:
        - nginx
        - nginx-selinux

    - name: Configure SELinux to allow NGINX proxy requests to ODA1 container (HTTP port {{ oda_http_port }})
      command: semanage port --add --type http_port_t --proto tcp {{ oda_http_port }}
      when: selinuxhttpports.stdout.find("{{ oda_http_port }}") == -1
      tags:
        - nginx
        - nginx-selinux

    - name: Configure SELinux to allow NGINX proxy requests to Kibana container (HTTP port {{ kibana_http_port }})
      command: semanage port --add --type http_port_t --proto tcp {{ kibana_http_port }}
      when: selinuxhttpports.stdout.find("{{ kibana_http_port }}") == -1
      tags:
        - nginx
        - nginx-selinux