---
- src: deveo@deus.solita.fi:Solita/projects/ansible-roles/repositories/git/solita-base
  scm: git

- src: deveo@deus.solita.fi:Solita/projects/ansible-roles/repositories/git/docker
  scm: git

- src: deveo@deus.solita.fi:Solita/projects/ansible-roles/repositories/git/nginx
  scm: git

- src: deveo@deus.solita.fi:Solita/projects/ansible-roles/repositories/git/scs-repos
  scm: git

- src: deveo@deus.solita.fi:Solita/projects/ansible-roles/repositories/git/keepalived
  scm: git

- src: https://github.com/solita/ansible-role-solita.jenkins.git
  version: v1.3.1
  name: solita.jenkins
  scm: git