FROM docker.elastic.co/logstash/logstash:5.4.0
#RUN rm -f /usr/share/logstash/pipeline/logstash.conf
#COPY pipeline/logstash.conf /usr/share/logstash/pipeline/
#COPY config/logstash.yml /usr/share/logstash/config/

